export const SEED_CATEGORIES = [
  { slug: "90s-nostalgia", name: "90s Nostalgia", description: "Film grain, disposable cameras, and faded colour.", position: 1 },
  { slug: "professional", name: "Professional Portfolio", description: "Clean headshots for a CV or a profile.", position: 2 },
  { slug: "cinematic", name: "Cinematic Portraits", description: "Dramatic light and colour grading.", position: 3 },
  { slug: "vintage", name: "Vintage Photography", description: "Decades of analogue looks.", position: 4 },
  { slug: "anime", name: "Anime Styles", description: "Illustrated and animated treatments.", position: 5 },
  { slug: "social", name: "Social Media Trends", description: "Whatever is filling the feed this week.", position: 6 },
  { slug: "fashion", name: "Fashion & Lifestyle", description: "Editorial styling and studio light.", position: 7 },
] as const;

export const SEED_TEMPLATES = [
  {
    slug: "90s-disposable-camera",
    title: "90s Disposable Camera",
    description: "Harsh flash, soft focus, and the date stamp in the corner.",
    prompt: "Transform this photo into a 1990s disposable camera snapshot: direct on-camera flash, slight overexposure on the face, warm colour cast, visible film grain, soft focus at the edges, and an orange date stamp in the lower right corner. Preserve the subject's face and identity exactly.",
    categorySlug: "90s-nostalgia",
    isTrending: true,
    position: 1,
  },
  {
    slug: "linkedin-headshot",
    title: "Studio Headshot",
    description: "Neutral backdrop, soft key light, business attire.",
    prompt: "Turn this photo into a professional studio headshot: soft large key light from the front left, subtle fill, neutral mid-grey seamless backdrop, business-casual attire, sharp focus on the eyes, natural skin texture retained. Preserve the subject's face and identity exactly.",
    categorySlug: "professional",
    isTrending: true,
    position: 2,
  },
  {
    slug: "teal-orange-cinematic",
    title: "Cinematic Teal & Orange",
    description: "Blockbuster colour grade with deep shadows.",
    prompt: "Regrade this photo as a cinematic film still: teal shadows, warm orange skin tones, low-contrast lifted blacks, anamorphic widescreen framing, shallow depth of field, subtle lens flare. Preserve the subject's face and identity exactly.",
    categorySlug: "cinematic",
    isTrending: true,
    position: 3,
  },
  {
    slug: "polaroid-1970s",
    title: "1970s Polaroid",
    description: "Washed pastels inside a white instant frame.",
    prompt: "Render this photo as a 1970s Polaroid instant print: washed-out pastel colours, low contrast, slight magenta shift, soft vignette, gentle blur, and the characteristic thick white instant-film border. Preserve the subject's face and identity exactly.",
    categorySlug: "vintage",
    isTrending: false,
    position: 4,
  },
  {
    slug: "anime-cel-shaded",
    title: "Anime Cel Shaded",
    description: "Hand-drawn animation styling with flat colour.",
    prompt: "Redraw this photo as a modern anime illustration: clean ink linework, flat cel shading with hard shadow edges, large expressive eyes, simplified background with soft gradient, vibrant saturated palette. Keep the subject's hairstyle, clothing, and recognisable features.",
    categorySlug: "anime",
    isTrending: true,
    position: 5,
  },
  {
    slug: "golden-hour-glow",
    title: "Golden Hour Glow",
    description: "Backlit sun flare and warm rim light.",
    prompt: "Relight this photo as golden-hour outdoor portrait: low warm sun behind the subject creating a rim light on hair and shoulders, soft haze, gentle lens flare, warm highlights and cool shadows, dreamy bokeh background. Preserve the subject's face and identity exactly.",
    categorySlug: "social",
    isTrending: false,
    position: 6,
  },
  {
    slug: "editorial-fashion",
    title: "Editorial Fashion",
    description: "High-contrast studio styling for a magazine page.",
    prompt: "Restyle this photo as a high-fashion editorial shot: hard directional studio light with crisp shadows, high contrast, desaturated background, confident styling, sharp detail in fabric texture, magazine-cover composition. Preserve the subject's face and identity exactly.",
    categorySlug: "fashion",
    isTrending: false,
    position: 7,
  },
  {
    slug: "vhs-camcorder",
    title: "VHS Camcorder",
    description: "Scanlines, tracking noise, and a timestamp overlay.",
    prompt: "Transform this photo into a frame from a 1980s VHS home video: visible horizontal scanlines, chromatic bleed on edges, tracking distortion band, low resolution softness, slightly green-shifted colour, and a white timestamp overlay in the corner. Preserve the subject's face and identity exactly.",
    categorySlug: "90s-nostalgia",
    isTrending: false,
    position: 8,
  },
] as const;
